[package]
name = "password_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
base64 = "0.22"
rand = "0.9.1"
aes-gcm = "0.10"
argon2 = "0.5"
rfd = "0.15.3"
