name: Build Windows MSVC

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust MSVC
        run: |
          rustup default stable
          rustup target add x86_64-pc-windows-msvc

      - name: Build
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-msvc-binary
          path: target/x86_64-pc-windows-msvc/release/*.exe
